/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 scene.gltf 
Author: mister dude (https://sketchfab.com/misterdude)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/iphone-14-pro-5cb0778041a34f09b409a38c687bb1d4
Title: Iphone 14 Pro
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function IPhone(props) {
  const { nodes, materials } = useGLTF('./iphone.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Material} scale={13.669} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
